### ISSUE TITLE
动态更新问题

### ISSUE THREAD

**Issue by oksimple** [zhoukekestar/weex-quick-start#6]
我跑了一个小demo 是把 hello.js 放在assets 下的我不明白 这个放在本地 怎么做到动态更新呢？

**Comment by zhoukekestar** [comment]
需要动态更新的话，你可以吧`hello.js`放在服务器上，在需要展现页面的时候，下载这个js文件，并展示就行了。需要更新的话，只需要更新服务器上的`hello.js`就行了。

**Comment by oksimple** [comment]
比如我当前已经打开了一个 activity  没有问题，但是后台更新了js 那么 意味着我必须下次进来的时候才能更新吗？

**Comment by oksimple** [comment]
谢谢 回复

**Comment by zhoukekestar** [comment]
是的，你可以做更好的用户体验：
1、需要加上合适的文件缓存机制
2、文件加载时加必要的加载动画等等
