### ISSUE TITLE
混淆怎么配置

### ISSUE THREAD

**Issue by wincentytg** [zhoukekestar/weex-quick-start#7]

**Comment by zhoukekestar** [comment]
你想问的问题可能不在这个项目的讨论范围，你可能需要去weex官方论坛提问。
不过，我在想你可能是想问`js bundle`的代码混淆，这个只需要对最终的`js bundle`代码做一次混淆就行了。类似的工具有[uglifyjs](https://github.com/mishoo/UglifyJS2)
